name: Build and Deploy with Gulp
on:
  push:
    branches: ["main"]
  
  # Allow manual triggering of the workflow from the GitHub Actions tab
  workflow_dispatch:

# Set permissions for the GITHUB_TOKEN to allow pushing to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure that only one deployment runs at a time to prevent conflicts
concurrency:
  group: "pages"
  cancel-in-progress: false

# Define the jobs for building and deploying the site
jobs:
  # Build the site using Gulp
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deploy the built site to GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4